package com.example.dao.common;

import com.example.model.FlywaySchemaHistory;
import com.example.model.FlywaySchemaHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FlywaySchemaHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    long countByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int deleteByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int deleteByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int insert(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int insertSelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    List<FlywaySchemaHistory> selectByExample(FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    FlywaySchemaHistory selectByPrimaryKey(Integer installedRank);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") FlywaySchemaHistory record, @Param("example") FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByExample(@Param("record") FlywaySchemaHistory record, @Param("example") FlywaySchemaHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByPrimaryKeySelective(FlywaySchemaHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flyway_schema_history
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByPrimaryKey(FlywaySchemaHistory record);
}