package com.example.dao.common;

import com.example.model.OrderSummary;
import com.example.model.OrderSummaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface OrderSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    long countByExample(OrderSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int deleteByExample(OrderSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int insert(OrderSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int insertSelective(OrderSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    List<OrderSummary> selectByExample(OrderSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    OrderSummary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderSummary record, @Param("example") OrderSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByExample(@Param("record") OrderSummary record, @Param("example") OrderSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByPrimaryKeySelective(OrderSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_summary
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    int updateByPrimaryKey(OrderSummary record);
}