server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/warehouse
    username: root
    password:

logging:
  level:
    root: INFO
    com.example: DEBUG
    spring: INFO
