package com.example.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class FlywaySchemaHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_rank
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer installedRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.version
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.description
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.type
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.script
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String script;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.checksum
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer checksum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_by
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String installedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.installed_on
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Date installedOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.execution_time
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer executionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flyway_schema_history.success
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Boolean success;
}