package com.example.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class OrderSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.request_time
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Date requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.cancel_flag
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Boolean cancelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.user_id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.zip
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String zip;
}