package com.example.model;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.effective_period_start
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Date effectivePeriodStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.effective_period_end
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Date effectivePeriodEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.division
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer division;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.supplier_id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer supplierId;
}