package com.example.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.product_id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.warehouse_id
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer warehouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_count
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.avaliable_count
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer avaliableCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.allocated_count
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer allocatedCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.unallocated_count
     *
     * @mbg.generated Sun Sep 30 21:13:13 CST 2018
     */
    private Integer unallocatedCount;
}